#!/usr/bin/env bash
#
# MyFactory installer foundation.
#
# Intended future usage:
#   curl -sSL https://domain.com/cli/install | bash
#
# Behavior:
#   - Installs or updates MyFactory core into ~/.myfactory/core
#   - Creates a `myfactory` shim in ~/.local/bin
#   - Never requires root, never stores secrets, never deletes user data.
#
# Configuration via environment variables:
#   MYFACTORY_REPO_URL   Git URL of myfactory-core (required for remote install)
#   MYFACTORY_HOME       Install root (default: ~/.myfactory)
#   MYFACTORY_BIN_DIR    Shim directory (default: ~/.local/bin)
#   MYFACTORY_REF        Git branch/tag to install (default: main)

set -euo pipefail

MYFACTORY_HOME="${MYFACTORY_HOME:-$HOME/.myfactory}"
MYFACTORY_BIN_DIR="${MYFACTORY_BIN_DIR:-$HOME/.local/bin}"
MYFACTORY_REF="${MYFACTORY_REF:-main}"
CORE_DIR="$MYFACTORY_HOME/core"

log() { printf '[myfactory-install] %s\n' "$*"; }
fail() { printf '[myfactory-install] ERROR: %s\n' "$*" >&2; exit 1; }

find_python() {
    for candidate in python3 python; do
        if command -v "$candidate" >/dev/null 2>&1; then
            if "$candidate" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 9) else 1)' >/dev/null 2>&1; then
                printf '%s' "$candidate"
                return 0
            fi
        fi
    done
    return 1
}

PYTHON_BIN="$(find_python)" || fail "Python 3.9+ is required but was not found on PATH."
command -v git >/dev/null 2>&1 || fail "git is required but was not found on PATH."

# --- Obtain or update the core checkout -------------------------------------

if [ -z "${MYFACTORY_REPO_URL:-}" ]; then
    # No repo URL. If we are running from inside a local checkout, install from it.
    script_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 && pwd || true)"
    if [ -n "$script_dir" ] && [ -f "$script_dir/../myfactory/cli.py" ]; then
        log "MYFACTORY_REPO_URL is not set; installing from local checkout."
        CORE_DIR="$(cd "$script_dir/.." && pwd)"
    else
        cat >&2 <<'EOF'
[myfactory-install] MYFACTORY_REPO_URL is not set.

Set it to the Git URL of the myfactory-core repository and re-run, e.g.:

    export MYFACTORY_REPO_URL=https://github.com/YOUR_ORG/myfactory-core.git
    curl -sSL https://domain.com/cli/install | bash

Or, from a local clone of myfactory-core:

    bash scripts/install-local.sh
EOF
        exit 1
    fi
else
    mkdir -p "$MYFACTORY_HOME"
    if [ -d "$CORE_DIR/.git" ]; then
        log "Updating existing install in $CORE_DIR"
        git -C "$CORE_DIR" fetch --quiet origin "$MYFACTORY_REF"
        git -C "$CORE_DIR" checkout --quiet "$MYFACTORY_REF"
        git -C "$CORE_DIR" pull --ff-only --quiet origin "$MYFACTORY_REF" \
            || log "WARNING: could not fast-forward; local changes preserved."
    elif [ -e "$CORE_DIR" ] && [ -n "$(ls -A "$CORE_DIR" 2>/dev/null)" ]; then
        fail "$CORE_DIR exists and is not a git checkout. Move it aside and re-run."
    else
        log "Cloning $MYFACTORY_REPO_URL (ref: $MYFACTORY_REF) into $CORE_DIR"
        git clone --quiet --branch "$MYFACTORY_REF" "$MYFACTORY_REPO_URL" "$CORE_DIR"
    fi
fi

[ -f "$CORE_DIR/myfactory/cli.py" ] || fail "Install looks broken: $CORE_DIR/myfactory/cli.py not found."

# --- Create the shim ---------------------------------------------------------

mkdir -p "$MYFACTORY_BIN_DIR"
SHIM="$MYFACTORY_BIN_DIR/myfactory"

cat > "$SHIM" <<EOF
#!/usr/bin/env bash
# MyFactory CLI shim (generated by scripts/install.sh — safe to regenerate).
export PYTHONPATH="$CORE_DIR\${PYTHONPATH:+:\$PYTHONPATH}"
exec "$PYTHON_BIN" -m myfactory "\$@"
EOF
chmod +x "$SHIM"

log "Installed core:  $CORE_DIR"
log "Installed shim:  $SHIM"

# --- PATH guidance -----------------------------------------------------------

case ":$PATH:" in
    *":$MYFACTORY_BIN_DIR:"*)
        log "Done. Try: myfactory --help"
        ;;
    *)
        cat <<EOF

$MYFACTORY_BIN_DIR is not on your PATH. Add it, e.g.:

    echo 'export PATH="$MYFACTORY_BIN_DIR:\$PATH"' >> ~/.bashrc && source ~/.bashrc

Then run: myfactory --help
EOF
        ;;
esac
